### PR TITLE
Pull Request ReDo

### PR DESCRIPTION
**Pull request by michaelwehrley**
* Resubmitting PR #80

### CODE REVIEW

**Comment by eschlange** [comment]
Only one question: for the feature spec, is there a reason for the feature spec be so large? Can it be broken down into more specific tasks or checks (ie: listening, recording, and view a meditation)?

**Comment by michaelwehrley** [comment]
@eschlange that is good point.  I will update.  Thanks.

**Comment by michaelwehrley** [comment]
@eschlange let me know if this is more clear et cetera: https://github.com/NU-CBITS/marigold/blob/msw_temp/spec/features/participant/meditations_spec.rb

**Comment by eschlange** [comment]
:shipit:

**Pull request merged**
