### PR TITLE
Add Meditation Images

### PR DESCRIPTION
**Pull request by michaelwehrley**
* Add back in meditation images
* Update view to display images

[#117549109]
[Finishes: #119837015]

### CODE REVIEW

**Comment by ericcf** [comment]
@michaelwehrley just make sure you run these images through https://imageoptim.com/mac. It can cut out a huge amount of bloat in images which is nice for faster loading pages.

**Comment by eschlange** [comment]
Solid.

**Comment by ericcf** [comment]
@eschlange did you see my comment? I didn't see any responses to it before you merged.

**Comment by michaelwehrley** [comment]
@eschlange @ericcf I am on it and will update it.

**Pull request merged**
